### ISSUE TITLE
cuelang.org: Chinese Translation Tracker

### ISSUE THREAD

**Issue by h1z3y3** [cue-lang/cue#1984]
Related to https://github.com/cue-lang/cue/issues/970

I'm going to work on Chinese translation.
I list all the subdirectories to track the progress.

If someone wants to contribute one of them, please comment this issue.

- [x] about https://github.com/cue-lang/cuelang.org/pull/238
- [ ] concepts
    - [ ] language
    - [ ] packages
    - [ ] patterns
    - [ ] scripting
- [x] contribution_guidelines https://github.com/cue-lang/cuelang.org/pull/217
- [ ] examples
- [x] install https://github.com/cue-lang/cuelang.org/pull/217
- [ ] integrations
- [ ] references
- [ ] tutorials
    - [ ] expressions
    - [ ] intro
    - [ ] packages
    - [ ] references
    - [ ] types
- [ ] usecases

**Comment by myitcv** [comment]
This issue was created against the "old" instance of https://cuelang.org. 

Work on translations for the new site is being tracked via https://github.com/cue-lang/cue/issues/3107, so closing this.

@h1z3y3 - thanks again for your original work here, as I said in https://github.com/cue-lang/cuelang.org/pull/238#issuecomment-2088251795.
